name = "KerrGeodesics"
uuid = "50190a2a-5e10-46bf-9224-e83f2e3ff1c3"
authors = []
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[extensions]
CalibrationExt = ["GLMakie", "NonlinearSolve", "Interpolations", "BenchmarkTools"]

[compat]
BenchmarkTools = "1.6.3"
GLMakie = "0.13.8"
Interpolations = "0.16.2"
NonlinearSolve = "4.12.0"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Enzyme", "Random", "BenchmarkTools"]
