name = "KerrGeodesics"
uuid = "cf9d6853-2dbf-4719-80af-949cd24590e4"
authors = ["ArchHem"]
version = "1.0.0-DEV"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
Adapt = "4.4.0"
BenchmarkTools = "1.6.0"
Colors = "0.13.1"
Enzyme = "0.13.86"
FastDifferentiation = "0.4.4"
Images = "0.26.2"
KernelAbstractions = "0.9.38"
LinearAlgebra = "1.11.0"
Plots = "1.41.1"
StaticArrays = "1.9.15"
VideoIO = "1.3.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
