name = "KerrGeodesics"
uuid = "cf9d6853-2dbf-4719-80af-949cd24590e4"
authors = ["ArchHem"]
version = "1.0.0-DEV"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Adapt = "4.4.0"
BenchmarkTools = "1.6.0"
Enzyme = "0.13.86"
FastDifferentiation = "0.4.4"
KernelAbstractions = "0.9.38"
LoopVectorization = "0.12.173"
Plots = "1.41.1"
StaticArrays = "1.9.15"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
